<?php

namespace Saman\ShoppingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProgressRepository extends EntityRepository
{
}
