<?php

namespace Saman\ShoppingBundle\Entity\Repository;

use Doctrine\ORM\Query;
use Saman\Library\Doctrine\BaseEntityRepository;
use Saman\UserBundle\Entity\User;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends BaseEntityRepository
{
    /**
     * Load item by its ID
     * 
     * @param type $id
     * @return type
     */
    public function loadItem($value, $key = 'id')
    {
        return $this->getItem($value, $key, true);
    }
        
    /**
     * General get item function, by default it just gets one or null object.
     * 
     * @param type $url
     * @param type $readOnly
     * @return type
     */
    public function getItem($value, $key = 'id', $loadItem = false)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('order')
            ->from('SamanShoppingBundle:Order', 'order')
            ->where(sprintf('order.%s = :%s AND order.deleted = 0', $key, $key))
            ->setParameter($key, $value);

        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
        
        return $result;
    }    
    
    /**
     * Get all items
     * 
     * @param type $order
     * @param type $readOnly
     * @return type
     */
    public function getItems($param = array(), $justQuery = true, $order = 'order.id', $readOnly = true)
    {
        $hydrationMode = $readOnly? Query::HYDRATE_ARRAY : null;
        $qb = $this->getQueryBuilder();
        
        $qb->select('order')
            ->from('SamanShoppingBundle:Order', 'order')
            ->where('order.deleted = 0')
            ->search('order.title', $param)
            ->orderBy($order);
        
        $query = $qb->getQuery();
        if ($justQuery) {
            return $query;
        } else {
            $result = $query->getResult($hydrationMode);
            return $result;
        }
    }
    
    /**
     * Get all user's orders
     * 
     * @param User $user
     * @param type $readOnly
     * @return type
     */
    public function getUserOrders(User $user, $readOnly = true)
    {
        $hydrationMode = $readOnly? Query::HYDRATE_ARRAY : null;
        $qb = $this->getQueryBuilder();
        
        $qb->select('d')
            ->from('SamanShoppingBundle:Order', 'd')
            ->leftJoin('d.progresses', 'progress', 'WITH', 'progress.deleted = 0')
            ->where('d.deleted = 0 AND d.user = :user')
            ->setParameter('user', $user);
        
        return $qb->getQuery()->getResult();
        
    }    
}