<?php

namespace ShoppingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    /**
     * General get item function, by default it just gets one or null object.
     * 
     * @param type $value
     * @param type $key
     * @return type
     */
    public function getPayment($value, $key = 'id')
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('op')
            ->from('ShoppingBundle:OrderPayment', 'op')
            ->where(sprintf('op.%s = :%s AND op.deleted = 0', $key, $key))
            ->setParameter($key, $value);

        $query = $qb->getQuery();
        
        return $query->getOneOrNullResult();
    }    
}