<?php

namespace PlaygroundBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LinkWidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkWidgetRepository extends EntityRepository
{
}
