<?php

namespace PlaygroundBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WelcomeWidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WelcomeWidgetRepository extends EntityRepository
{
}
