parameters:
    saman_shopping.shopping.class: Saman\ShoppingBundle\Service\ShoppingService

services:
    saman_shopping.shopping:
        class: %saman_shopping.shopping.class%
        arguments: [@saman.helper, @saman_media.media, @saman_config.config, %saman_shopping.shopping%]
        
    saman_shopping.product.form:
        class: Saman\ShoppingBundle\Form\ProductForm
        arguments: [@saman.helper]
        tags:
            - { name: form.type, alias: saman_shopping_product_form }
    