parameters:
    saman_config.config:
        numberOfItemsPerPage: 10
        configs:
            security:
                type: public
                title: configs.security.title
                description: configs.security.description
                icon: configs.security.icon
                options:
                    salt:
                        type: text
                        label: configs.general.options.title.title
                        description: configs.general.options.title.description
                        grid: col-md-4
                        default: false

            general:
                type: public
                title: configs.general.title
                description: configs.general.description
                icon: configs.general.icon
                options:
                    defultTheme:
                        type: entity
                        class: 'SamanAppearanceBundle:Theme' 
                        label: configs.general.options.theme.title
                        description: configs.general.options.theme.description
                        default: ""
                    title:
                        type: text
                        label: configs.general.options.title.title
                        description: configs.general.options.title.description
                        default: "title"
                    email:
                        type: email
                        label: configs.general.options.email.title
                        description: configs.general.options.email.description
                        default: "saman@gmail.com"
            view:
                type: private
                title: configs.view.title
                description: configs.view.description
                icon: configs.view.icon
                options:
                    salt:
                        type: choice
                        choices:
                            m: Male
                            f: Female
                        label: configs.general.options.title.title
                        description: configs.general.options.title.description
                        default: f                       