# Note:
# The following routes should be placed before the CMS bundle route, otherwise 
# they will be treated as CMS rout page
saman_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    
saman_login_check:
    path: /login_check
    
saman_logout:
    path: /logout

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
    

saman_app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

saman_media:
    resource: "@MediaBundle/Resources/config/routing.yml"
    prefix:   /

saman_label:
    resource: "@LabelBundle/Resources/config/routing.yml"
    prefix:   /

saman_cms:
    resource: "@CmsBundle/Resources/config/routing.yml"
    prefix:   /

saman_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /