# Note:
# The following routes should be placed before the CMS bundle route, otherwise 
# they will be treated as CMS rout page
saman_api:
    type: rest
    resource: "routing_rest.yml"
    prefix : /api    
  
saman_login:
    path:     /login/{isWeb}
    defaults: { _controller: AppBundle:Security:login, isWeb: false }
saman_login_check:
    path: /admin/login_check
saman_logout:
    path: /admin/logout
  
saman_login_web:
    path:     /shopp/login/{isWeb}
    defaults: { _controller: AppBundle:Security:login, isWeb: true }
saman_login_check_web:
    path: /shopping/login_check
saman_logout_web:
    path: /shopping/logout

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
saman_app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

saman_shopping:
    resource: "@ShoppingBundle/Resources/config/routing.yml"
    prefix:   /

#saman_playground:
#    resource: "@PlaygroundBundle/Resources/config/routing.yml"
#    prefix:   /playground
    
saman_media:
    resource: "@MediaBundle/Resources/config/routing.yml"
    prefix:   /

saman_label:
    resource: "@LabelBundle/Resources/config/routing.yml"
    prefix:   /

saman_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
saman_product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /

saman_cms:
    resource: "@CmsBundle/Resources/config/routing.yml"
    prefix:   /