#api_product:
#    type: rest
#    resource: ProductBundle\Controller\ProductApiController

api_product_show_products:
    path:     /products
    defaults: { _controller: ProductBundle:ProductApi:getProducts }
    requirements:
        _method: GET
    
api_product_show_product:
    path:     /product/{productId}
    defaults: { _controller: ProductBundle:ProductApi:getProduct }
    requirements:
        _method: GET
        
api_product_show_test_product:
    path:     /product/test/{productId}
    defaults: { _controller: ProductBundle:ProductAdminApi:getProduct }
    requirements:
        _method: GET

api_product_add_product:
    path:     /product
    defaults: { _controller: ProductBundle:ProductAdminApi:addProduct }
    requirements:
        _method: POST
        
api_product_edit_product:
    path:     /product/{productId}
    defaults: { _controller: ProductBundle:ProductAdminApi:editProduct }    
    requirements:
        _method: POST