saman_app:
    resource: "@SamanAppBundle/Resources/config/routing.yml"
    prefix:   /

saman_login:
    path:     /login
    defaults: { _controller: SamanSecurityBundle:Security:login }
    
saman_login_check:
    path: /login_check
    
saman_logout:
    path: /logout

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"    


    
saman_media:
    resource: "@SamanMediaBundle/Resources/config/routing.yml"
    prefix:   /

saman_label:
    resource: "@SamanLabelBundle/Resources/config/routing.yml"
    prefix:   /

saman_cms:
    resource: "@SamanCmsBundle/Resources/config/routing.yml"
    prefix:   /

saman_security:
    resource: "@SamanSecurityBundle/Resources/config/routing.yml"
    prefix:   /

saman_user:
    resource: "@SamanUserBundle/Resources/config/routing.yml"
    prefix:   /