#api_product:
#    type: rest
#    resource: ProductBundle\Controller\ProductApiController

api_product_show_products:
    path:     /products/{page}/{_format}
    defaults: { _controller: ProductBundle:Api\ProductApi:getProducts, page: 0, _format: json }
    requirements:
        _method: GET
    
api_product_show_product:
    path:     /product/{id}
    defaults: { _controller: ProductBundle:Api\ProductApi:getProduct }
    requirements:
        _method: GET
        
api_admin_product_show_product:
    path:     /admin/product/{productId}
    defaults: { _controller: ProductBundle:Api\ProductAdminApi:getProduct }
    requirements:
        _method: GET

api_admin_product_get_product_form:
    path:     /form/admin/product/{productId}
    defaults: { _controller: ProductBundle:Api\ProductAdminApi:getProductForm, productId: null }
    requirements:
        _method: GET

api_admin_product_add_product:
    path:     /admin/product
    defaults: { _controller: ProductBundle:Api\ProductAdminApi:addProduct }
    requirements:
        _method: POST
        
api_admin_product_edit_product:
    path:     /admin/product/{productId}
    defaults: { _controller: ProductBundle:Api\ProductAdminApi:editProduct }    
    requirements:
        _method: POST