jms_security_extra:
    secure_all_services: false
    expressions: true
    
security:
    encoders:
        UserBundle\Entity\User:
            id: saman.md5encoder
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    providers:
        administrators:
            entity: { class: UserBundle:User }

    firewalls:
        secured_area:
            pattern:   ^/admin
            anonymous: ~
            provider: administrators
            form_login:
                login_path: saman_login
                check_path: saman_login_check
            logout:
                path:   saman_logout
                target: saman_login
                
        secured_area_web:
            pattern:   ^/shopping|media
            anonymous: ~
            provider: administrators
            form_login:
                login_path: saman_login_web
                check_path: saman_login_check_web
            logout:
                path:   saman_logout_web
                target: saman_login_web
                
    access_control:
        #- { path: ^/admin/, roles: ROLE_ADMIN, requires_channel: https } 
        - { path: ^/admin/, roles: ROLE_ADMIN }
        # Include the following line to also secure the /admin path itself
        - { path: ^/admin$, roles: ROLE_ADMIN }
        #- { path: ^/shopping/, roles: ROLE_USER, requires_channel: https } 
        - { path: ^/shopping/, roles: ROLE_USER }
        - { path: ^/media/, roles: ROLE_USER }
      