<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\Query;
use Library\Doctrine\BaseEntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends BaseEntityRepository
{   
    /**
     * 
     * @param type $orderId
     * @param User $user
     * @return type
     */
    public function getEvents($entityPathId, $entityPathName, $triggers = array())
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('e')
            ->from('AppBundle:Event', 'e')
            ->leftJoin('e.user', 'u')
            ->where('e.entityPathId = :entityPathId AND e.entityPathName = :entityPathName')
            ->setParameter('entityPathId', $entityPathId)
            ->setParameter('entityPathName', $entityPathName);

        return $qb->getQuery()->getResult();
    }
}