<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\Query;
use Library\Doctrine\BaseEntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends BaseEntityRepository
{   
    
}