<?php

namespace AppBundle\Entity\Repository;

use Library\Doctrine\BaseEntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemConfigRepository extends BaseEntityRepository
{
    /**
     * Get config options
     * 
     * @param type $key
     * @return type
     */
    public function getConfigOptions($key)
    {
        $qb = $this->getQueryBuilder()
            ->select('sc.options')
            ->from('AppBundle:SystemConfig', 'sc')
            ->where('sc.key = :key')
            ->setParameter('key', $key);

        return $qb->getQuery()->getSingleScalarResult();
    }
    
    /**
     * Get one config entity
     * 
     * @param type $key
     * @return \AppBundle\Entity\SystemConfig
     */
    public function getConfig($key)
    {
        $qb = $this->getQueryBuilder()
            ->select('sc')
            ->from('AppBundle:SystemConfig', 'sc')
            ->where('sc.key = :key')
            ->setParameter('key', $key);

        return $qb->getQuery()->getOneOrNullResult();
    }    
}