parameters:
#    saman_security.example.class: Saman\SecurityBundle\Example

services:
#    saman_security.example:
#        class: %saman_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
