<?php

namespace MediaBundle\Entity\Repository;

use Library\Doctrine\BaseEntityRepository;
use Doctrine\ORM\Query;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends BaseEntityRepository
{
    /**
     * Load item by its ID
     * 
     * @param type $id
     * @return type
     */
    public function loadItem($value, $key = 'id')
    {
        return $this->getItem($value, $key, true);
    }
        
    /**
     * General get item function, by default it just gets one or null object.
     * 
     * @param type $id
     * @param type $loadAsArray
     * @return type
     */
    public function getItem($id, $loadAsArray = false)
    {
        if ($loadAsArray) {
            $qb = $this->getQueryBuilder()
                ->select('media.id, media.title, media.path, IDENTITY(media.user), media.visibility, media.isPermanent')
                ->from('MediaBundle:Media', 'media')
                ->where('media.id = :id AND media.deleted = 0')
                ->setParameter('id', $id);

            $result = $qb->getQuery()->getScalarResult();
            $row = reset($result);
        
            return $row? $row : null;
        } else {
            $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('media')
                ->from('MediaBundle:Media', 'media')
                ->where('media.id = :id AND media.deleted = 0')
                ->setParameter('id', $id);

            $query = $qb->getQuery();
            return $query->getOneOrNullResult();
        }
    }    
    
    /**
     * Get all items
     * 
     * @param type $order
     * @param type $readOnly
     * @return type
     */
    public function getItems($param = array(), $justQuery = true, $order = 'media.id', $readOnly = true)
    {
        $hydrationMode = $readOnly? Query::HYDRATE_ARRAY : null;
        $qb = $this->getQueryBuilder();
        
        $qb->select('media')
            ->from('MediaBundle:Media', 'media')
            ->where('media.deleted = 0')
            ->search('media.title', $param)
            ->orderBy($order);
        
        $query = $qb->getQuery();
        if ($justQuery) {
            return $query;
        } else {
            $result = $query->getResult($hydrationMode);
            return $result;
        }
    }
    
    /**
     * Get items by ID
     * 
     * @param type $ids
     * @param type $readOnly
     * @param type $justQuery
     * @return Media[]
     */
    public function getItemsByID($ids, $readOnly = true)
    {
        $hydrationMode = $readOnly? Query::HYDRATE_ARRAY : null;
        $qb = $this->getQueryBuilder();
        
        $qb->select('media')
            ->from('MediaBundle:Media', 'media')
            ->where('media.id IN (:ids)')
            ->setParameter('ids', $ids);
        
        return $qb->getQuery()->getResult($hydrationMode);
    }
}