saman_media_upload_temp_media:
    path:     /media/upload-media
    defaults: { _controller: MediaBundle:Media:uploadMedia, isPermanent: false }

saman_media_download_media:
    path:     /media/download-media
    defaults: { _controller: MediaBundle:Media:downloadMedia }
    
saman_media_delete_media:
    path:     /media/delete-media
    defaults: { _controller: MediaBundle:Media:deleteMedia }

#TODO: this rout should use /admin/    
saman_selec2_data_url:
    path:     /select2/data_url/{class}
    defaults: { _controller: MediaBundle:Select2:select2Data }
    
#TODO: this rout should use /admin/
saman_selec2_data_lookup_url:
    path:     /select2/data_lookup_url/{class}
    defaults: { _controller: MediaBundle:Select2:select2DataLookup }