saman_media_download_media:
    path:     /media/download-media
    defaults: { _controller: MediaBundle:Media:downloadMedia, isAdmin: false }
    
saman_media_upload_temp_media:
    path:     /shopping/media/upload-media
    defaults: { _controller: MediaBundle:Media:uploadMedia, isPermanent: false, isAdmin: false }

saman_media_delete_media:
    path:     /shopping/media/delete-media
    defaults: { _controller: MediaBundle:Media:deleteMedia, isAdmin: false }

saman_admin_media_download_media:
    path:     /admin/media/download-media
    defaults: { _controller: MediaBundle:Media:downloadMedia, isAdmin: true }

saman_admin_media_upload_temp_media:
    path:     /admin/media/upload-media
    defaults: { _controller: MediaBundle:Media:uploadMedia, isPermanent: false, isAdmin: true }
    
saman_admin_media_delete_media:
    path:     /admin/media/delete-media
    defaults: { _controller: MediaBundle:Media:deleteMedia, isAdmin: true }



#TODO: this rout should use /admin/    
saman_selec2_data_url:
    path:     /admin/select2/data_url/{class}
    defaults: { _controller: MediaBundle:Select2:select2Data }
    
#TODO: this rout should use /admin/
saman_selec2_data_lookup_url:
    path:     /admin/select2/data_lookup_url/{class}
    defaults: { _controller: MediaBundle:Select2:select2DataLookup }