parameters:
    saman_shopping_payment: ~
    saman_shopping_order:
        numberOfItemsPerPage: 10
        orderPriceCalculation:
            customOrder:
                factor: 1        
        orderStructure:
            dpi:
                type: choice
                choices:
                    1: 100
                    2: 200
                    3: 300
                    4: 400
                label: DPI (Raj)
                default: 1
                required: true
            colors:
                type: choice
                choices:
                    1: Black & With
                    2: Rust
                    3: Colorful
                label: Color
                default: 1
                required: true
            numberOfColors:
                type: choice
                choices:
                    1: 10
                    2: 20
                    3: 30
                label: Number Of Colors
                default: 1
                required: true
            width:
                type: text
                label: Width (cm)
                default: ""
                required: true
            height:
                type: text
                label: Height (cm)
                default: ""
                required: true