saman_shopping_customer_profile:
    path:     /shopping/myprofile
    defaults: { _controller: ShoppingBundle:Customer:displayProfile }

saman_shopping_customer_joinus:
    path:     /shopp/joinus
    defaults: { _controller: ShoppingBundle:Customer:register }
    
saman_shopping_customer_joinus_confirmation:
    path:     /shopp/joinus/confirmation/{userId}
    defaults: { _controller: ShoppingBundle:Customer:registerConfirmation }
    
    
    
    
saman_shopping_order_payment:
    path:     /shopping/order/payment/{orderId}
    defaults: { _controller: ShoppingBundle:Payment:orderPayment }
    
saman_shopping_order_payment_confirmation:
    path:     /shopping/order/payment/confirm/{paymentId}
    defaults: { _controller: ShoppingBundle:Payment:orderPaymentConfirmation }
    
    
    

saman_shopping_orders:
    path:     /shopping/orders
    defaults: { _controller: ShoppingBundle:Shopping:displayOrders }

saman_shopping_order_display:
    path:     /shopping/order/show/{orderId}
    defaults: { _controller: ShoppingBundle:Shopping:displayOrder }
    
saman_shopping_order_add:
    path:     /shopping/order/create
    defaults: { _controller: ShoppingBundle:Shopping:addEditOrder, orderId: null }

saman_shopping_order_add_confirmation:
    path:     /shopping/order/confirm/{orderId}
    defaults: { _controller: ShoppingBundle:Shopping:orderConfirmation }
    
saman_shopping_order_set_shipping_address:
    path:     /shopping/order/shipping/{orderId}
    defaults: { _controller: ShoppingBundle:Shopping:setShippingAddress, orderId: null }

saman_shopping_order_edit:
    path:     /shopping/order/update/{orderId}
    defaults: { _controller: ShoppingBundle:Shopping:addEditOrder }
   
saman_shopping_order_delete:
    path:     /shopping/order/delete/{itemId}
    defaults: { _controller: ShoppingBundle:Shopping:deleteOrder }