saman_shopping_customer_profile:
    path:     /shopping/myprofile
    defaults: { _controller: ShoppingBundle:Customer:displayProfile }



saman_shopping_orders:
    path:     /shopping/order
    defaults: { _controller: ShoppingBundle:Shopping:displayOrders }

saman_shopping_order_display:
    path:     /shopping/order/{itemId}
    defaults: { _controller: ShoppingBundle:Shopping:displayOrder }
    
saman_shopping_order_add:
    path:     /shopping/order/add
    defaults: { _controller: ShoppingBundle:Shopping:addOrder }

saman_shopping_order_edit:
    path:     /shopping/order/edit/{itemId}
    defaults: { _controller: ShoppingBundle:Shopping:editOrder }
   
saman_shopping_order_delete:
    path:     /shopping/order/delete/{itemId}
    defaults: { _controller: ShoppingBundle:Shopping:deleteOrder }