saman_shopping_customer_profile:
    path:     /shopping/myprofile
    defaults: { _controller: ShoppingBundle:Customer:displayProfile }

saman_shopping_customer_joinus:
    path:     /shopp/joinus
    defaults: { _controller: ShoppingBundle:Customer:joinus }
    
saman_shopping_customer_joinus_confirmation:
    path:     /shopp/joinus/confirmation
    defaults: { _controller: ShoppingBundle:Customer:joinusConfirmation }
    
    

saman_shopping_orders:
    path:     /shopping/order
    defaults: { _controller: ShoppingBundle:Shopping:displayOrders }

saman_shopping_order_display:
    path:     /shopping/order/show/{itemId}
    defaults: { _controller: ShoppingBundle:Shopping:displayOrder }
    
saman_shopping_order_add:
    path:     /shopping/order
    defaults: { _controller: ShoppingBundle:Shopping:addEditOrder, orderId: null }

saman_shopping_order_add_confirmation:
    path:     /shopping/order/confirmation/{orderId}
    defaults: { _controller: ShoppingBundle:Shopping:orderConfirmation }
    
saman_shopping_order_set_shipping_address:
    path:     /shopping/order/shipping/{orderId}
    defaults: { _controller: ShoppingBundle:Shopping:setShippingAddress, orderId: null }

saman_shopping_order_edit:
    path:     /shopping/order/update/{orderId}
    defaults: { _controller: ShoppingBundle:Shopping:addEditOrder }
   
saman_shopping_order_delete:
    path:     /shopping/order/delete/{itemId}
    defaults: { _controller: ShoppingBundle:Shopping:deleteOrder }