services:
    saman_shopping.shopping:
        class: ShoppingBundle\Service\ShoppingService
        arguments: 
            - @saman.appService
            - @saman.eventHandler
            - @saman_shopping.orderProgressHandler
            - @saman.payment
            - %saman_shopping_order%
  
    saman_shopping.orderProgressHandler:
        class: ShoppingBundle\Service\OrderProgressHandler
        arguments: 
            - @saman.appService
            - %saman_shopping_order%