Saman\ShoppingBundle\Entity\Product:
    # Validation the entire Page, The error message in form will display as
    constraints:
        - Saman\ShoppingBundle\Validator\Constraints\ValidProduct: ~    
    properties:
        title:
            - Length:
                min: 5
                max: 50
                minMessage: "Your first name must be at least {{ limit }} characters long"
                maxMessage: "Your first name cannot be longer than {{ limit }} characters long"                