<?php

namespace Saman\LabelBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRepository extends EntityRepository
{
}