saman_admin_product_home:
    path:     /admin/product
    defaults: { _controller: ProductBundle:Product:displayProducts }
    
saman_admin_product_display:
    path:     /admin/product/{productId}
    defaults: { _controller: ProductBundle:Product:displayProduct }    
   
saman_admin_product_add:
    path:     /admin/add/product/
    defaults: { _controller: ProductBundle:Product:addEditProduct, productId: null }

saman_admin_product_edit:
    path:     /admin/edit/product/{productId}
    defaults: { _controller: ProductBundle:Product:addEditProduct }
    
saman_admin_product_delete:
    path:     /admin/delete/product/{productId}
    defaults: { _controller: ProductBundle:Product:deleteProduct }