saman_admin_product_home:
    path:     /admin/product
    defaults: { _controller: ProductBundle:ProductAdmin:displayProducts }
    
saman_admin_product_display:
    path:     /admin/product/show/{productId}
    defaults: { _controller: ProductBundle:ProductAdmin:displayProduct }    
   
saman_admin_product_add:
    path:     /admin/product/add/
    defaults: { _controller: ProductBundle:ProductAdmin:addEditProduct, productId: null }

saman_admin_product_edit:
    path:     /admin/product/edit/{productId}
    defaults: { _controller: ProductBundle:ProductAdmin:addEditProduct }
    
saman_admin_product_delete:
    path:     /admin/product/delete/{productId}
    defaults: { _controller: ProductBundle:ProductAdmin:deleteProduct }
    
    
    
saman_admin_product_configs:
    path:     /admin/product/configs
    defaults: { _controller: ProductBundle:ProductAdminConfig:configProducts }
    
saman_admin_product_category_delete:
    path:     /admin/product/configs/category/delete/{categoryId}
    defaults: { _controller: ProductBundle:ProductAdminConfig:deleteCategory }
    
saman_admin_product_category_addedit:
    path:     /admin/product/configs/category/update/{categoryId}
    defaults: { _controller: ProductBundle:ProductAdminConfig:addEditCategory, categoryId: null }

saman_admin_product_specification_field_delete:
    path:     /admin/product/configs/specificationfield/delete/{fieldKey}
    defaults: { _controller: ProductBundle:ProductAdminConfig:deleteSpecificationField }
    
saman_admin_product_specification_field_addedit:
    path:     /admin/product/configs/specificationfield/update/{fieldKey}
    defaults: { _controller: ProductBundle:ProductAdminConfig:addEditSpecificationField, fieldKey: null }
    
    
saman_shopping_product_home:
    path:     /shop/gallery
    defaults: { _controller: ProductBundle:Product:displayProducts }

saman_shopping_product_display:
    path:     /shop/gallery/show/{productId}
    defaults: { _controller: ProductBundle:Product:displayProduct }