saman_admin_user_home:
    path:     /admin/user
    defaults: { _controller: SamanUserBundle:User:displayUsers }
    
saman_admin_myprofile:
    path:     /admin/myprofile
    defaults: { _controller: SamanUserBundle:User:myprofile }
   
saman_admin_user_add:
    path:     /admin/user/add
    defaults: { _controller: SamanUserBundle:User:addEditUser, userId: null }

saman_admin_user_edit:
    path:     /admin/user/edit/{userId}
    defaults: { _controller: SamanUserBundle:User:addEditUser }
    
saman_admin_user_delete:
    path:     /admin/user/delete/{userId}
    defaults: { _controller: SamanUserBundle:User:deleteUser }