parameters:
#    saman_user.example.class: Saman\UserBundle\Example

services:
#    saman_user.example:
#        class: %saman_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
