services:
    saman.appService:
        class: AppBundle\Service\AppService
        public: false
        arguments: 
            - @translator.default 
            - @security.context
            - @form.factory
            - @router
            - @templating
            - @doctrine.orm.default_entity_manager
            - @knp_paginator
            - @validator
            - @saman.session
            - %saman.helper.param%
            
    saman.eventHandler:
        class: AppBundle\Service\EventHandler
        arguments: [@saman.appService]
        
    saman.payment:
        class: AppBundle\Service\PaymentService
        arguments: 
            - @saman.appService
            - @saman.eventHandler           