<?php

namespace Saman\ShoppingBundle\Repository;

use Saman\Library\Doctrine\BaseEntityRepository;
use Saman\Library\Map\EntityMap;
use Doctrine\ORM\Query;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends BaseEntityRepository
{
    /**
     * Load item by its ID
     * 
     * @param type $id
     * @return type
     */
    public function loadItem($value, $key = 'id')
    {
        return $this->getItem($value, $key, true);
    }
        
    /**
     * General get item function, by default it just gets an object.
     * 
     * @param type $url
     * @param type $readOnly
     * @return type
     */
    public function getItem($value, $key = 'id', $loadItem = false)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('product')
            ->from(EntityMap::SHOPPING_PRODUCT, 'product')
            ->where(sprintf('product.%s = :%s AND product.deleted = 0', $key, $key))
            ->setParameter($key, $value);

        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
        
        return $result;
    }    
    
    /**
     * Get all items
     * 
     * @param type $order
     * @param type $readOnly
     * @return type
     */
    public function getItems($param = array(), $justQuery = true, $order = 'product.id', $readOnly = true)
    {
        $hydrationMode = $readOnly? Query::HYDRATE_ARRAY : null;
        $qb = $this->getQueryBuilder();
        
        $qb->select('product')
            ->from(EntityMap::SHOPPING_PRODUCT, 'product')
            ->where('product.deleted = 0')
            ->search('product.title', $param)
            ->orderBy($order);
        
        $query = $qb->getQuery();
        if ($justQuery) {
            return $query;
        } else {
            $result = $query->getResult($hydrationMode);
            return $result;
        }
    }
}