saman_cms_admin_page_home:
    path:     /admin/cms/page
    defaults: { _controller: SamanCmsBundle:CmsAdmin:displayPages}
    
saman_cms_admin_page_add:
    path:     /admin/cms/page/add
    defaults: { _controller: SamanCmsBundle:CmsAdmin:addPage }

saman_cms_admin_page_edit:
    path:     /admin/cms/page/edit/{itemId}
    defaults: { _controller: SamanCmsBundle:CmsAdmin:editPage }

saman_cms_admin_page_display:
    path:     /admin/cms/page/{itemId}
    defaults: { _controller: SamanCmsBundle:CmsAdmin:displayPage }
    
saman_cms_admin_page_delete:
    path:     /admin/cms/page/delete/{itemId}
    defaults: { _controller: SamanCmsBundle:CmsAdmin:deletePage }
    
    
    
saman_cms_page_index:
    path:     /
    defaults: { _controller: SamanCmsBundle:CmsView:index, url: ''}

saman_cms_page:
    path:     /{url}
    defaults: { _controller: SamanCmsBundle:CmsView:index, url: ''}
    requirements: 
        url: (?!admin|media|shopping|product)(.+)