services:
    saman_cms.cms.admin:
        class: Saman\CmsBundle\Service\CmsAdminService
        arguments: [@saman.baseService, %saman_cms.cms.admin%]
        
    saman_cms.cms.view:
        class: Saman\CmsBundle\Service\CmsViewService
        arguments: [@saman.baseService, %saman_cms.cms%]    