<?php

namespace ProductBundle\Entity\Repository;

use Library\Doctrine\BaseEntityRepository;
use Doctrine\ORM\Query;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends BaseEntityRepository
{   
    /**
     * 
     * @param int $id
     * @return type
     */
    public function getProductForView($id)
    {
        $qb = $this->getQueryBuilder()
            ->select(''
                . 'product.id, '
                . 'product.title, '
                . 'product.description,'
                . 'product.price'
                )
            ->from('ProductBundle:Product', 'product')
            ->where('product.id = id AND product.deleted = 0')
            ->setParameter('id', $id);

        $result = $qb->getQuery()->getScalarResult();
        $row = reset($result);
        
        return $row? $row : null;
    }
    
    /**
     * 
     * @return type
     */
    public function getProductsListForView()
    {
        $qb = $this->getQueryBuilder()
            ->select(''
                . 'product.id, '
                . 'product.title, '
                . 'product.description,'
                . 'product.price'
                )
            ->from('ProductBundle:Product', 'product')
            ->where('product.deleted = 0')
            ->orderBy('product.title');
        
        return $qb->getQuery()->getScalarResult();
    }
        
    /**
     * Get one or null product
     * 
     * @param type $value
     * @param type $key
     * @return NULL|Product
     */
    public function getProduct($value, $key = 'id')
    {
        $qb = $this->getQueryBuilder()
            ->select('product')
            ->from('ProductBundle:Product', 'product')
            ->where(sprintf('product.%s = :%s AND product.deleted = 0', $key, $key))
            ->setParameter($key, $value);

        return $qb->getQuery()->getOneOrNullResult();
    }    
    
    /**
     * Get all products
     * 
     * @param type $order
     * @param type $readOnly
     * @return type
     */
    public function getProducts($param = array(), $justQuery = true, $order = 'product.id', $readOnly = true)
    {
        $hydrationMode = $readOnly? Query::HYDRATE_ARRAY : null;
        $qb = $this->getQueryBuilder()
            ->select('product')
            ->from('ProductBundle:Product', 'product')
            ->where('product.deleted = 0')
            ->search('product.title', $param)
            ->orderBy($order);
        
        $query = $qb->getQuery();
        if (!$justQuery) {
            return $query->getResult($hydrationMode);        
        }
        
        return $query;
    }
}