<?php

namespace Saman\AppearanceBundle\Repository;

use Doctrine\ORM\Query;
use Saman\Library\Doctrine\BaseEntityRepository;
use Saman\Library\Map\EntityMap;

/**
 * NavigationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavigationRepository extends BaseEntityRepository
{
    /**
     * Load item by its ID
     * 
     * @param type $id
     * @return type
     */
    public function loadNavigation($value, $key = 'id')
    {
        return $this->getNavigation($value, $key, true);
    }
        
    /**
     * General get item function, by default it just gets one or null object.
     * 
     * @param type $url
     * @param type $readOnly
     * @return type
     */
    public function getNavigation($value, $key = 'id', $loadNavigation = false)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        if ($loadNavigation) {
            $qb->select('navigation, link')
                ->from(EntityMap::APPEARANCE_NAVIGATION, 'navigation')
                ->leftJoin('navigation.links', 'link', 'WITH', 'link.deleted = 0')    
                ->where(sprintf('navigation.%s = :%s AND navigation.deleted = 0', $key, $key))
                ->setParameter($key, $value);
        } else {
            $qb->select('navigation')
                ->from(EntityMap::APPEARANCE_NAVIGATION, 'navigation')
                ->where(sprintf('navigation.%s = :%s AND navigation.deleted = 0', $key, $key))
                ->setParameter($key, $value);
        }

        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
        
        return $result;
    }    
    
    /**
     * Get all items
     * 
     * @param type $order
     * @param type $readOnly
     * @return type
     */
    public function getNavigations($param = array(), $justQuery = true, $order = 'navigation.id', $readOnly = true)
    {
        $hydrationMode = $readOnly? Query::HYDRATE_ARRAY : null;
        $qb = $this->getQueryBuilder();
        
        $qb->select('navigation')
            ->from(EntityMap::APPEARANCE_NAVIGATION, 'navigation')
            ->where('navigation.deleted = 0')
            ->search('navigation.title', $param)
            ->orderBy($order);
        
        $query = $qb->getQuery();
        if ($justQuery) {
            return $query;
        } else {
            $result = $query->getResult($hydrationMode);
            return $result;
        }
    }
    
    /**
     * 
     * @param type $navigationsId
     * @param type $loadJustQuery
     */
    public function getNavigationsById($navigationsId, $readOnly = false)
    {
        $hydrationMode = $readOnly? Query::HYDRATE_ARRAY : null;
        $qb = $this->getQueryBuilder();
        
        $qb->select('navigation')
            ->from(EntityMap::APPEARANCE_NAVIGATION, 'navigation')
            ->where('navigation.deleted = 0 AND navigation.id IN(:navigationsId)')
            ->setParameter('navigationsId', $navigationsId);
        
        return $qb->getQuery()->getResult($hydrationMode);
    }
}