<?php

namespace Saman\AppearanceBundle\Repository;

use Doctrine\ORM\Query;
use Saman\Library\Doctrine\BaseEntityRepository;
use Saman\Library\Map\EntityMap;

/**
 * WidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetRepository extends BaseEntityRepository
{
    /**
     * General get item function, by default it just gets one or null object.
     * 
     * @param type $url
     * @param type $readOnly
     * @return type
     */
    public function getWidget($value, $key = 'id')
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('widget')
            ->from(EntityMap::APPEARANCE_WIDGET, 'widget')
            ->where(sprintf('widget.%s = :%s AND widget.deleted = 0', $key, $key))
            ->setParameter($key, $value);

        $query = $qb->getQuery();
        $result = $query->getOneOrNullResult();
        
        return $result;
    }    
    
    /**
     * Get all items
     * 
     * @param type $order
     * @param type $readOnly
     * @return type
     */
    public function getWidgets($param = array(), $justQuery = true, $order = 'widget.id', $readOnly = true)
    {
        $hydrationMode = $readOnly? Query::HYDRATE_ARRAY : null;
        $qb = $this->getQueryBuilder();
        
        $qb->select('widget')
            ->from(EntityMap::APPEARANCE_WIDGET, 'widget')
            ->where('widget.deleted = 0')
            ->search('widget.title', $param)
            ->orderBy($order);
        
        $query = $qb->getQuery();
        if ($justQuery) {
            return $query;
        } else {
            $result = $query->getResult($hydrationMode);
            return $result;
        }
    }
}