<?php

namespace UserBundle\Entity\Repository;

use Library\Doctrine\BaseEntityRepository;
use UserBundle\Entity\User;

/**
 * UserActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActivityRepository extends BaseEntityRepository
{
    /**
     * Get user activities
     * 
     * @param User $user
     * @return type
     */
    public function getUserActivities(User $user)
    {
        $conn = $this->getEntityManager()->getConnection();
        
        $query = sprintf(
            "SELECT type, MAX(time) as time, COUNT(id) as count FROM saman_user_activity WHERE "
            . "user_id = %d GROUP BY type ", 
            $user->getId()
            );
        
        $stmt = $conn->prepare($query);
        $stmt->execute();
            
        return $stmt->fetchAll();
    }    
}
