parameters:

services:
    saman_appearance.theme:
        class: Saman\AppearanceBundle\Service\ThemeService
        arguments: [@saman.helper, @saman_media.media, %saman_appearance.theme%]
        
    saman_appearance.navigation:
        class: Saman\AppearanceBundle\Service\NavigationService
        arguments: [@saman.helper, %saman_appearance.theme%]
        
    saman_appearance.link:
        class: Saman\AppearanceBundle\Service\LinkService
        arguments: [@saman.helper, %saman_appearance.theme%]
        
    saman_appearance.widget:
        class: Saman\AppearanceBundle\Service\WidgetService
        arguments: [@saman.helper, @saman_media.media, %saman_appearance.theme%]
        
    saman_appearance.form.theme:
        class: Saman\AppearanceBundle\Form\ThemeForm
        arguments: [@saman.helper, %saman_appearance.theme%]
        tags:
            - { name: form.type, alias: saman_appearance_theme_form }
            
    saman_appearance.form.navigation:
        class: Saman\AppearanceBundle\Form\NavigationForm
        arguments: [@saman.helper]
        tags:
            - { name: form.type, alias: saman_appearance_navigation_form }
            